[lint]

extend-select = [
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "DJ", # flake8-django
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "FBT", # flake8-boolean-trap
    "I",   # isort
    "INT",  # flake8-gettext
    "PIE", # flake8-pie
    "PGH", # pygrep-hooks
    "S",   # flake8-bandit
    "SIM", # flake8-simplify
    "W",   # pycodestyle warnings
    "YTT",   # flake8-2020
    "UP",  # pyupgrade
    "RUF100",  # unused noqa
]

extend-ignore = [
    "E501",  # no line length errors
]

fixable = ["C4", "E", "F", "I", "UP"]

[lint.isort]
known-first-party = ["src", "wagtailmarkdown"]
lines-between-types = 1
lines-after-imports = 2

[format]
docstring-code-format = true
